services:

  # Redis
  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: always

  # Database Postgres
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rehpostgre1
    container_name: postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

# Django Application
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8001:8001
    image: app:django
    container_name: djano_app
    command: python manage.py runserver 0.0.0.0:8001
    depends_on:
      db:
        condition: service_healthy
  
  # Celery:
  celery:
    build: .
    command: celery -A core worker -l DEBUG
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - db
      - redis
      
volumes:
  postgres_data: